---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность просмотра товаров в каталоге постранично.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Пользователь должен иметь возможность зарегистрироваться в интернет-магазине.
  - Пользователь должен иметь возможность увеличивать фото товара для просмотра.
  - У пользователя должен быть личный кабинет, где он может указывать свои контактные данные для дальнейшей связи менеджера магазина по вопросам корректировки, доставки или оплаты заказа.
